# Generated by Django 4.2.1 on 2023-05-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='name',
            new_name='first_name',
        ),
    ]
