# Generated by Django 4.2.1 on 2023-05-22 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_name_data_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='first_name',
            new_name='name',
        ),
    ]
