# Generated by Django 4.2.1 on 2023-05-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_rename_first_name_data_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='number_phone',
            field=models.CharField(max_length=10),
        ),
    ]
