# Generated by Django 4.1.7 on 2023-04-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='synccontent',
            index=models.Index(fields=['content_type', 'object_id'], name='sync_syncco_content_42caac_idx'),
        ),
    ]
